name: flutter_app
description: A new flutter project.
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^8.2.0
  charts_flutter: ^0.6.0
  http: ^0.12.1


flutter:

  uses-material-design: true

  assets:
    - assets/sytody.png
    - assets/logo.png
    - assets/login-logo.png